name: rich_text_html_editor
description: RichEditor for Flutter` is a beautiful Rich Text `WYSIWYG Editor` for Android and iOS.
version: 1.0.1
homepage: https://github.com/daolq3012/rich_text_editor

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.7.2+3
  flutter_lints: ^2.0.1

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/rich_text_html_editor/assets/editor/editor.html
    - packages/rich_text_html_editor/assets/editor/normalize.css
    - packages/rich_text_html_editor/assets/editor/rich_editor.js
    - packages/rich_text_html_editor/assets/editor/style.css
